apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.wordpress.name }}
type: Opaque
data:
    WORDPRESS_DB_NAME: ZGFsZXhhbmRyYQ== 
    WORDPRESS_DB_USER: dWFsZXhhbmRyYQ==
    WORDPRESS_DB_PASSWORD: cGFsZXhhbmRyYQ==
