apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  labels:
    app: {{ .Values.wordpress.name }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.wordpress.name }}
  type: ClusterIP
