apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.name }}
type: Opaque
data:
    MYSQL_DATABASE: ZGFsZXhhbmRyYQ== 
    MYSQL_USER: dWFsZXhhbmRyYQ==
    MYSQL_PASSWORD: cGFsZXhhbmRyYQ==
    MYSQL_ROOT_PASSWORD: cGFsZXhhbmRyYQ==
