apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 3306
      targetPort: {{ .Values.name }}
