name: Wordpress Workflow

on: push

jobs:
  wordpress-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Helm template
        run: |
          ls -alh
          helm template . | kubectl apply -f -



