name: Wordpress Workflow

on: 
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: wordpress # Add your deployment name here.

jobs:
  wordpress-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: ls -alh

      - name: Checkout
        uses: actions/checkout@v1

      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Deploy
        run: helm template . | kubectl apply -f -






