name: Wordpress Workflow

on: push

jobs:
  wordpress-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Helm template
        run: |
          ls -alh
      - name: Checkout
        uses: actions/checkout@v1
      - name: List again files after checkout
        run: 
          ls -alh



